name: Deploy and Trigger load_data_to_snowflake Function

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        install_components: 'gsutil'

    # Deploy load_data_to_snowflake function
    - name: Deploy load_data_to_snowflake Function
      run: |
        gcloud functions deploy load-data-to-snowflake-function \
          --runtime python311 \
          --trigger-http \
          --allow-unauthenticated \
          --entry-point load_data_to_snowflake \
          --project ${{ secrets.GCP_PROJECT_ID }} \
          --region us-central1 \
          --service-account github-gcs-snowflake-sync@my-gcp-project-433206.iam.gserviceaccount.com \
          --no-gen2

    # Trigger load_data_to_snowflake function
    - name: Trigger load_data_to_snowflake Function
      run: |
        curl -X POST https://us-central1-${{ secrets.GCP_PROJECT_ID }}.cloudfunctions.net/load-data-to-snowflake-function
