name: Deploy and Trigger load_data_to_snowflake Function

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: hopeful-host-433910-d8
        install_components: 'gsutil'

    # Deploy load_data_to_snowflake function
    - name: Deploy load_data_to_snowflake Function
      run: |
        gcloud functions deploy load-data-to-snowflake-function \
          --runtime python311 \
          --trigger-http \
          --allow-unauthenticated \
          --entry-point load_data_to_snowflake \
          --project hopeful-host-433910-d8 \
          --region us-central1 \
          --service-account new-service@hopeful-host-433910-d8.iam.gserviceaccount.com \
          --no-gen2

    # Upload the Customer.yml file to the GCS bucket
    - name: Sync files with GCS
      run: |
        gsutil -m rsync -r -d . gs://mydata_upload_bucket/
