name: Trigger load_data_to_snowflake Function

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        install_components: 'gsutil'

    # Trigger the load_data_to_snowflake function
    - name: Trigger load_data_to_snowflake Function
      run: |
        curl -X POST https://REGION-YOUR_PROJECT_ID.cloudfunctions.net/load-data-to-snowflake-function
