name: Deploy and Update Google Cloud Function

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Sync files with GCS
      run: |
        gsutil -m rsync -r -d ./Loading_yaml gs://mydata_upload_bucket/


    - name: Sync files with actual-data-upload-bucket
      run: |
        gsutil -m rsync -r -d ./Process_yaml gs://actual-data-upload-bucket/
