name: Deploy and Update Google Cloud Function

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Sync files with GCS
      run: |
        gsutil -m rsync -r ./Customer gs://mydata_upload_bucket/Customer/

    - name: Deploy Google Cloud Function
      run: |
        gcloud functions deploy load-data-to-snowflake-function \
          --runtime python311 \
          --trigger-resource mydata_upload_bucket \
          --trigger-event google.storage.object.finalize \
          --allow-unauthenticated \
          --entry-point load_data_to_snowflake \
          --region us-central1 \
          --project ${{ secrets.GCP_PROJECT_ID }} \
          --service-account new-service@hopeful-host-433910-d8.iam.gserviceaccount.com

    - name: Verify Deployment
      run: |
        gcloud functions describe load-data-to-snowflake-function --region us-central1
